import tkinter as tk

root = tk.Tk()
root.title("TracSat Ground Station")
root.geometry("900x150")
#root.resizable(width=False, height=False)
root.minsize(width=900, height=150)

command = tk.Label(root, text="Command:")
currentlyTransmitting = tk.Label(root, text="Sending:")
currentTransmission = tk.Label(root, text="No Transmission", fg="red")
commandEntry = tk.Entry(root)
transmit = tk.Button(root, text ="Transmit", width = 26)
stop = tk.Button(root, text ="Stop")
reset = tk.Button(root, text ="Reset")
abort = tk.Button(root, text ="Abort")
pause = tk.Button(root, text ="Pause", width = 15)
resetMissionClock = tk.Button(root, text ="Reset Mission Clock")
extrabutton1 = tk.Button(root, text ="Self Destruct")
extrambutton2 = tk.Button(root, text ="extrabutton2")
groundstationSoftware = tk.Label(root, text="Tracsat Ground Station Software \n Version 1.0.0 \n Copyright 2020. All Rights Reserved. \n Tracsat is a subsidiary of GA Electromagnetic Systems.")

command.grid(row=0,column =0, pady=5)
currentlyTransmitting.grid(row=2,column =0, sticky="W")
currentTransmission.grid(row=2,column =1, pady=5, sticky="W")
commandEntry.grid(row=0,column =1, pady=5, padx=15)
transmit.grid(row=1,columnspan = 2, pady=5)
#stop.grid(row=1,column = 1,  pady=5)
reset.grid(row=0,column = 2, pady=5, padx=5)
abort.grid(row=1,column = 2, pady=5, padx=5)
pause.grid(row=0,column = 3, pady=5, padx=5)
resetMissionClock.grid(row=1,column = 3, pady=5, padx=5)
extrabutton1.grid(row=0,column = 4, pady=5, padx=5)
extrambutton2.grid(row=1,column = 4, pady=5, padx=5)
groundstationSoftware.grid(row = 0, rowspan=2,column = 5, sticky="NE", pady=5,)
root.grid_columnconfigure(5, weight=1)


tk.mainloop()